#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#define ECP_SHORTWEIERSTRASS
#define MBEDTLS_AES_C
#define MBEDTLS_AESNI_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_X86_64
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_SHA256_C

#include <limits.h>
#include <stddef.h>
#include <stdlib.h>

#define MBEDTLS_ENTROPY_HARDWARE_ALT

#endif
